name: frontend
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.2
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.6.0
  get: ^4.6.6
  font_awesome_flutter: ^10.7.0
  flutter_islamic_icons: ^1.0.2
  get_storage: any
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2
  image_picker: ^1.0.4
  flutter_launcher_icons: ^0.13.1
  lottie: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:


  uses-material-design: true

  fonts:
    - family: Beiruti
      fonts:
        - asset: assets/fonts/Beiruti-VariableFont_wght.ttf

    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-VariableFont_slnt,wght.ttf

    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Regular.ttf

    - family: TNR
      fonts:
        - asset: assets/fonts/times-new-roman.ttf

  assets:
    - assets/icons/
    - assets/images/