const express = require('express');
const router = express.Router();
const studentsController = require('../controllers/StudentController');
const userauth = require('../middleware/UserAuth');
const studentauth = require('../middleware/StudentAuth');

router.post('/login', studentsController.login);
router.get('/getallstudents',userauth, studentsController.getallstudents);
router.get('/getstudentbyhalaqatid',userauth, studentsController.getstudentbyhalaqatid);
router.put('/updateme',userauth, studentsController.updateme);
router.put('/updatestudent',userauth, studentsController.updatestudent);
router.post('/addnewstudent',userauth, studentsController.addnewstudent);
router.delete('/deletestudent',userauth, studentsController.deletestudent);
router.get('/getstudentbyid',userauth, studentsController.getstudentbyid);
router.get('/getstudentsbyname',userauth, studentsController.getstudentsbyname);
router.put('/stopstudent',userauth, studentsController.stopstudent);
router.put('/dismissstudent',userauth, studentsController.dismissstudent);
router.put('/startstudent',userauth, studentsController.startstudent);
router.get('/getstopedanddismissedstudents',userauth, studentsController.getstopedanddismissedstudents);
router.put('/movestudenttoanotherhalakat',userauth, studentsController.movestudenttoanotherhalakat);
router.get('/getstudentscountinarea',userauth, studentsController.getstudentscountinarea);
router.get('/getstudentscountbycenter',userauth, studentsController.getstudentscountbycenter);
module.exports = router;
